### ISSUE TITLE
Optionally add location

### ISSUE THREAD

**Issue by mspiegel** [boyney123/evento#1]
Here is a gist https://gist.github.com/mspiegel/f420f70753684dbd7d70 to optionally add location information to the template of an event. I've included it immediately below the line "From {{start_time}} to {{end_time}}". It only adds the location if present in the post. I can submit a pull request if that's easier I just found it simpler to create a gist. Thanks for creating the theme it's great! I've rebooted my blog and started using it https://nerdguidedc.com/

**Comment by boyney123** [comment]
Sweet! Glad to you your using it and glad its helpful.

If you could submit a pull request that would be great, and il add it in.
